// frontend/src/components/AppointmentFilter.jsx
import React, { useState } from 'react';
import './AppointmentFilter.css'; // Assuming some basic styling

const AppointmentFilter = ({ onApplyFilters, onClearFilters }) => {
    const [filters, setFilters] = useState({
        startDate: '',
        endDate: '',
        petName: '',
        ownerName: '',
        veterinarianId: '',
        status: '',
    });

    const handleChange = (e) => {
        const { name, value } = e.target;
        setFilters(prevFilters => ({
            ...prevFilters,
            [name]: value,
        }));
    };

    const handleApply = () => {
        // Basic client-side validation for dates
        if (filters.startDate && filters.endDate && new Date(filters.startDate) > new Date(filters.endDate)) {
            alert('Start date cannot be after end date.');
            return;
        }
        onApplyFilters(filters);
    };

    const handleClear = () => {
        setFilters({
            startDate: '',
            endDate: '',
            petName: '',
            ownerName: '',
            veterinarianId: '',
            status: '',
        });
        onClearFilters();
    };

    return (
        <div className="appointment-filter-card">
            <h3>Filter Appointments</h3>
            <div className="filter-grid">
                <div className="filter-group">
                    <label htmlFor="startDate">Start Date:</label>
                    <input
                        type="date"
                        id="startDate"
                        name="startDate"
                        value={filters.startDate}
                        onChange={handleChange}
                    />
                </div>
                <div className="filter-group">
                    <label htmlFor="endDate">End Date:</label>
                    <input
                        type="date"
                        id="endDate"
                        name="endDate"
                        value={filters.endDate}
                        onChange={handleChange}
                    />
                </div>
                <div className="filter-group">
                    <label htmlFor="petName">Pet Name:</label>
                    <input
                        type="text"
                        id="petName"
                        name="petName"
                        value={filters.petName}
                        onChange={handleChange}
                        placeholder="e.g., Buddy"
                    />
                </div>
                <div className="filter-group">
                    <label htmlFor="ownerName">Owner Name:</label>
                    <input
                        type="text"
                        id="ownerName"
                        name="ownerName"
                        value={filters.ownerName}
                        onChange={handleChange}
                        placeholder="e.g., Jane Doe"
                    />
                </div>
                <div className="filter-group">
                    <label htmlFor="veterinarianId">Veterinarian ID:</label>
                    <input
                        type="number"
                        id="veterinarianId"
                        name="veterinarianId"
                        value={filters.veterinarianId}
                        onChange={handleChange}
                        placeholder="e.g., 1"
                    />
                </div>
                <div className="filter-group">
                    <label htmlFor="status">Status:</label>
                    <select
                        id="status"
                        name="status"
                        value={filters.status}
                        onChange={handleChange}
                    >
                        <option value="">All</option>
                        <option value="SCHEDULED">Scheduled</option>
                        <option value="COMPLETED">Completed</option>
                        <option value="CANCELLED">Cancelled</option>
                        <option value="PENDING">Pending</option>
                    </select>
                </div>
            </div>
            <div className="filter-actions">
                <button onClick={handleApply} className="btn-primary">Apply Filters</button>
                <button onClick={handleClear} className="btn-secondary">Clear Filters</button>
            </div>
        </div>
    );
};

export default AppointmentFilter;

// src/main/resources/static/js/components/AppointmentFilter.vue
<template>
  <div class="appointment-filter card p-3 mb-3">
    <h5 class="card-title">Filter Appointments</h5>
    <form @submit.prevent="applyFilters">
      <div class="row g-3">
        <div class="col-md-6 col-lg-3">
          <label for="startDate" class="form-label">Start Date</label>
          <input type="date" class="form-control" id="startDate" v-model="filters.startDate">
        </div>
        <div class="col-md-6 col-lg-3">
          <label for="endDate" class="form-label">End Date</label>
          <input type="date" class="form-control" id="endDate" v-model="filters.endDate">
        </div>
        <div class="col-md-6 col-lg-3">
          <label for="petId" class="form-label">Pet ID</label>
          <input type="number" class="form-control" id="petId" v-model.number="filters.petId" placeholder="e.g., 1">
        </div>
        <div class="col-md-6 col-lg-3">
          <label for="ownerId" class="form-label">Owner ID</label>
          <input type="number" class="form-control" id="ownerId" v-model.number="filters.ownerId" placeholder="e.g., 1">
        </div>
        <div class="col-md-6 col-lg-3">
          <label for="veterinarianId" class="form-label">Veterinarian ID</label>
          <input type="number" class="form-control" id="veterinarianId" v-model.number="filters.veterinarianId" placeholder="e.g., 1">
        </div>
        <div class="col-md-6 col-lg-3">
          <label for="descriptionKeyword" class="form-label">Description Keyword</label>
          <input type="text" class="form-control" id="descriptionKeyword" v-model="filters.descriptionKeyword" placeholder="e.g., checkup">
        </div>
      </div>
      <div class="mt-3 d-flex justify-content-end">
        <button type="button" class="btn btn-secondary me-2" @click="clearFilters">Clear Filters</button>
        <button type="submit" class="btn btn-primary">Apply Filters</button>
      </div>
    </form>
  </div>
</template>

<script>
export default {
  name: 'AppointmentFilter',
  data() {
    return {
      filters: {
        startDate: null,
        endDate: null,
        petId: null,
        ownerId: null,
        veterinarianId: null,
        descriptionKeyword: ''
      }
    };
  },
  methods: {
    applyFilters() {
      this.$emit('apply-filters', this.filters);
    },
    clearFilters() {
      this.filters = {
        startDate: null,
        endDate: null,
        petId: null,
        ownerId: null,
        veterinarianId: null,
        descriptionKeyword: ''
      };
      this.$emit('clear-filters');
    }
  }
};
</script>

<style scoped>
/* Add some basic styling if needed */
.appointment-filter {
  background-color: #f8f9fa;
  border: 1px solid #e9ecef;
  border-radius: .25rem;
}
</style>
